* Unicode Esc

Emacs lisp supports Unicode codepoints in symbols, comments, strings
and character literals. Lisp also supports "escape" syntax in strings
and characters that express the Unicode codepoints entirely in 7bit
ASCII characters by using the hexadecimal codepoint, or the Unicode
character name. While these escape strings are safe for storage and
display regardless of the editor's frame, they are not visually
clear. The purpose of this package is to display the specified Unicode
character on the screen over the encoded escape string. It uses the
machinery provided by ~prettify-symbols-mode~ to display the Unicode
characters while storing the escape string.

* Unicode escapes

|---------------+-----------------------------------------------------|
| =Escape=        | =Description=                                         |
|---------------+-----------------------------------------------------|
| ~\N{char-name}~ | Display Unicode character from ~(char-from-name …)~   |
| ~\N{U+xx…xx}~   | Display Unicode character ~U+xx…xx~                   |
| ~\Uxxxx~        | Display Unicode character ~U+xxxx~ (4 hex digits)     |
| ~\Uxxxxxxxx~    | Display Unicode character ~U+xxxxxxxx~ (8 hex digits) |
|---------------+-----------------------------------------------------|
For example:
#+begin_example
              character: 🐕 (displayed as 🐕) (codepoint 128021, #o372025, #x1f415)
                charset: unicode (Unicode (ISO10646))
  code point in charset: 0x1F415
               to input: type "C-x 8 RET 1f415" or "C-x 8 RET DOG"
                   name: DOG
#+end_example

We can put a "dog" Unicode character into our elisp code either by
entering the codepoint directly into the buffer using the ~C-x 8 RET~
recipes described by =to input:= above; or by using one of the Unicode escape strings
supported by Emacs: ~\N{DOG}~ or ~\U0001f415~.

With this package enabled, a comment block in an elisp script that
contains the following:
#+begin_src emacs-lisp
  ;;
  ;; Examples:
  ;;   N escapes:   \N{Duck} \N{DUCK} \N{duck}
  ;;   N U+ escape: \N{U+1f986}
  ;;   U escape:    \U0001f986
  ;;   Literal:     🦆
  ;;
#+end_src
will look like the following:
#+begin_src emacs-lisp
  ;;
  ;; Examples:
  ;;   N escapes:   🦆 🦆 🦆
  ;;   N U+ escape: 🦆
  ;;   U escape:    🦆
  ;;   Literal:     🦆
  ;;
#+end_src


* Configuration
When ~unicode-esc-mode~ is enabled, it insures that
~prettify-symbols-mode~ is also enabled. Setting
~prettify-symbols-unprettify-at-point~ to a non-nil value will display
the underlying escape string rather than the Unicode character when
the cursor is on the character.

** Custom Variable: ~unicode-esc-char-name-default-case~
When ~\N{char-name}~ escapes are generated, the char-name is the Unicode
assigned name (or "old name"). Elisp ignores the letter-case of the
name so when we generate the escape, this variable identifies the
function which adjusted the letter-case of the official name. By
default, the name is capitalized, but it can be left as-is, up cased,
or down cased as well.

** Custom Variable: ~unicode-esc-default-escape-style~
By default, when escape strings are generated, they are ~\N{}~, but is
can be set to generate ~\U~ escapes or literal Unicode characters.

** Interactive function: ~unicode-esc-update-at-point~
If point is on a Unicode character or an escape sting, it will be
updated to the default escape style. If the function is invoked with a
prefix argument, you may choose the escape style for this invocation
only.

** Interactive function: ~unicode-esc-update-escapes~
This function loops through each Unicode character and escape string
in the buffer and updates them to the default escape style. If you
insert Unicode characters via =C-x 8 RET= in your buffer, you can then
replace them all with escapes easily. Like the "update at point"
function, when called with a prefix argument, you can choose what
escape style to use.

* Installation
Install the ~unicode-esc~ package as follows:
#+BEGIN_SRC emacs-lisp
    (use-package unicode-esc
      :vc ( :url "https://codeberg.org/mmauger/unicode-esc" )
      :hook (emacs-lisp-mode)
      )

#+END_SRC

#  LocalWords:  codepoints codepoint elisp
